### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by yc-zhang** [chechecarer/radarTechProject#1]
基本上实现了我们想要的效果（虽然有一大堆的小的界面问题，不过这个不着急），我觉得在进行 redux 学习之前，最好继续修改下这个实现比较好，最少是希望你能够将 react 这边的基础再巩固一下。

在点击注册或者登陆按钮后，希望提交一个 form 到后台，并且后台需要验证一些输入，再返回结果。比如说：手机号写的是字母的话，应该在提交后显示出`无效的号码`的错误信息。如果所有的认证都成功的话，可以跳转到第二个空白页面。

**Comment by chechecarer** [comment]
嗯，的确还存在很多问题，而且我对react还不太熟悉，那我就再修改修改，慢慢完善。
如果我有新的提交，你们随时给建议
